name: JSON file validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Set branch variable
        id: branch_var
        run: echo "branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Validate successfully reproduced breaking update JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/successful-reproduction-schemas/breaking-update.schema.json"
          file: "data/benchmark/*.json"
          refSchemasMap:
            '{"https://github.com/chains-project/breaking-updates/blob/main/schemas/successful-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/successful-reproduction-schemas/breaking-update-dependency.schema.json"}'

      - name: Validate reproduction failed breaking update JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/unsuccessful-reproduction-schemas/breaking-update.schema.json"
          file: "data/unsuccessful-reproductions/*.json"
          refSchemasMap:
            '{"https://github.com/chains-project/breaking-updates/blob/main/schemas/unsuccessful-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/unsuccessful-reproduction-schemas/breaking-update-dependency.schema.json"}'

      - name: Check if JSON files exist
        id: file_check
        run: |
          if find data/in-progress-reproductions -name "*.json" -print -quit | grep -q .; then
            echo "check_result=true" >> $GITHUB_OUTPUT
          else
            echo "check_result=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate not reproduced breaking update JSON
        if: steps.file_check.outputs.check_result == 'true'
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/not-attempted-reproduction-schemas/breaking-update.schema.json"
          file: "data/in-progress-reproductions/*.json"
          refSchemasMap:
            '{"https://raw.githubusercontent.com/${{ github.repository }}/${{ env.branch_name }}/schemas/not-attempted-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/not-attempted-reproduction-schemas/breaking-update-dependency.schema.json"}'
